# Generated by Django 5.0 on 2024-02-10 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='номер телефона'),
        ),
    ]
