# Generated by Django 5.0 on 2024-01-03 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateField(default='2023-01-03', verbose_name='дата создания'),
            preserve_default=False,
        ),
    ]
