# Generated by Django 5.0 on 2024-04-10 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0003_product_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('cancel_published', 'Может отменять публикацию')], 'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
    ]
