# Generated by Django 5.0 on 2024-04-10 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0004_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('cancel_published', 'Может отменять публикацию'), ('change_description', 'Может менять описание'), ('change_category', 'Может менять категорию')], 'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
    ]
