# Generated by Django 5.0 on 2024-01-27 22:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='заголовок')),
                ('slug', models.CharField(max_length=50, verbose_name='slug')),
                ('text', models.TextField(verbose_name='содержимое')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog_image/', verbose_name='изображение')),
                ('creation_date', models.DateField(default=datetime.datetime(2024, 1, 27, 22, 21, 39, 633433), verbose_name='дата создания')),
                ('is_published', models.BooleanField(default=False, verbose_name='опубликовано ли')),
                ('count_views', models.IntegerField(default=0, verbose_name='кол-во просмотров')),
            ],
            options={
                'verbose_name': 'блог',
                'verbose_name_plural': 'блог',
            },
        ),
    ]
